site_name: GeoDL EngDesign
site_url: https://anthonysirico.github.io/PyGeo-TMS-mkdocs.io

nav:
  - Home: index.md
  - About: about_me.md
  - Links: links.md
  - Publications: published_papers.md
  - Cited Works:

theme: readthedocs

plugins:
  - search
  - bibtex:
      bib_file: "References.bib"
      bib_dir: ./docs

markdown_extensions:
  - footnotes
