site_name: GeoDL EngDesign
site_url: https://anthonysirico.github.io/PyGeo-TMS-mkdocs.io

nav:
  - Home: index.md
  - About: about_me.md
  - Links: links.md
  - Publications: published_papers.md
  - Citations: citations.md

theme: readthedocs

plugins:
  - search

markdown_extensions:
  - footnotes
